### ISSUE TITLE
Storyboard issue

### ISSUE THREAD

**Issue by bariscck** [bhlvoong/LBTAComponents#1]
Hello Brian, how can I use this pod for storyboard ? I'm trying but I'm getting this fatal error ; 

`fatal error: init(coder:) has not been implemented: file /Users/***/Desktop/TwitterLBTA/Pods/LBTAComponents/LBTAComponents/Classes/DatasourceController.swift, line 54
`

**Comment by MikePT28** [comment]
You will not be able to use this with storyboard as there's no implementation for it.

**Comment by bariscck** [comment]
Thank you Mike.
