### ISSUE TITLE
pod file error

### ISSUE THREAD

**Issue by MansoorJafari** [bhlvoong/LBTAComponents#10]
Hi
I want to add LBTAComponents in my project but get below error

[!] Unable to satisfy the following requirements:

- `LBTAComponents` required by `Podfile`

Specs satisfying the `LBTAComponents` dependency were found, but they required a higher minimum deployment target.

please help.

**Comment by SwiftTsubame** [comment]
The minimum depolyment target of LBTAComponents is ios 9.1. Maybe your project supports older versions?

**Comment by ZacharyKhan** [comment]
As @SwiftTsubame said, make sure your minimum project dependency version is greater than 9.1. I would suggest setting your minimum deployment target to iOS 10 or higher. This can be changed under your project settings > General.
