### ISSUE TITLE
Why extending UICollcetionViewController?

### ISSUE THREAD

**Issue by Urkman** [bhlvoong/LBTAComponents#13]
This makes it unflexible...
For example I could not use it in a UIViewController.

Perhaps think about a way not extending a Controller.

**Comment by ZacharyKhan** [comment]
What is your issue exactly? 

Maybe we could help you achieve your goal and the UICollectionViewController is irrelevant. Who knows?

**Comment by bhlvoong** [comment]
Hmmmmmmmmmmmmmmmmmmmmmm, I'll put this into the bucket of questions that don't make much sense due to lack of understanding of UIKit.

**Comment by Urkman** [comment]
??? I would  like to use it on a CollectionView within a ViewController not a CollectionViewController.
How can i do this?

**Comment by ZacharyKhan** [comment]
@Urkman are you using a storyboard or are you instantiating your `UIViewController` and `UICollectionView` programmatically?

**Comment by Urkman** [comment]
Storyboards

**Comment by ZacharyKhan** [comment]
Can you post an error or a code snippet? I still don’t fully understand your issue.

**Comment by bhlvoong** [comment]
Are you using some kind of horizontal collection view? Most of the time you should be using just a UICollectionViewController.
