### ISSUE TITLE
iOS 8.0

### ISSUE THREAD

**Issue by mduenas** [bhlvoong/LBTAComponents#2]
Would it be possible to make it work on iOS 8.0 and above?

**Comment by MikePT28** [comment]
You most likely can. Just don't go with the framework as it is compiled for iOS 9.1+. Try copying all the classes to your project directly and see if that compiles without errors. If it does, you are set. If it does not, then just fix the errors, as they will most likely be methods that weren't available in iOS 8.

A word of advice: drop iOS 8 support. If the app is new, just support the latest version of iOS and 1 prior to that. In this case I would recommend just supporting iOS 10 & 9 though given the adoption rate for iOS 10 you could do just fine with iOS 10.

**Comment by mduenas** [comment]
Thanks for the response!  I looked into it a bit more and it's the anchors that aren't available in < iOS 9.0.  There are other projects out there that implement something similar to anchors.  I'm going to try and make these components backward compatible.  We recently dropped support for < iOS 8.0 and we won't be dropping support for 8.0 just yet.  Thanks!
