### ISSUE TITLE
Type 'NSAttributedStringKey' (aka 'NSString') has no member 'paragraphStyle'

### ISSUE THREAD

**Issue by nguye-2** [bhlvoong/LBTAComponents#20]
Hello Brian, first of all thank you for your good job on LBTAComponents. I am using it in my project and it makes the development so much easier ! 👍 

In NSMutableAttribtutedString+Helper.swift I got the following error : 

> Type 'NSAttributedStringKey' (aka 'NSString') has no member 'paragraphStyle'

<img width="636" alt="capture d ecran 2017-09-23 a 11 08 07" src="https://user-images.githubusercontent.com/7138295/30771803-ce2ce212-a04f-11e7-836e-69d9c5b70e15.png">

I am using Swift3 and upgraded xcode 8.2 to 9.

Finally I upgraded to swift 4 and replaced NSAttributedStringKey.paragraphStyle with .paragraphStyle.

I close the issue

**Comment by hyunsooo** [comment]
Hi, I had the same issue using Swift3 and xcode 9 (not-yet updated) 
so, I tried to solve it replacing value from NSAttributedStringKey.paragraphStyle to NSParagraphStyleAttributedName (its string). and it works.

**Comment by bhlvoong** [comment]
Try to run 'pod update' and get the latest LBTAComponents for Swift 4.
