### ISSUE TITLE
Multiple API request on same datasource

### ISSUE THREAD

**Issue by jaksatomovic** [bhlvoong/LBTAComponents#22]
so how can i make it work with two api request...i have one for section 0 (fetcUserData where i got json response) and second for section 1 (fetchUserFeed)  but olny one of them is showing depending which is called first in controller

**Comment by ZacharyKhan** [comment]
Can you provide a code snippet? I feel like this issue is beyond the scope of LBTAComponents, but I can still try to help you out and get this issue squashed 👍 .

**Comment by bhlvoong** [comment]
This is definitely out of scope. You just need to fire off two requests chained together and construct your own datasource object on completion.
