### ISSUE TITLE
No such module 'LBTAComponent'

### ISSUE THREAD

**Issue by andriaripratama** [bhlvoong/LBTAComponents#26]
Hi!

I'm following Brian Tutorial for Twitter App now (2018). I try to use LBTAComponents version on that video. I follow all step and got me error on No Such Module LBTAComponents. I already open .xcworkspace. Then I try to use up-to-date version of it, but still the error coming up.

Is there any solution for this? Thanks

**Comment by agu3rra** [comment]
I have this repository from the time I went thru the Twitter app tutorial earlier this year. Check if it compiles without the error and if so, try to compare differences with your project (like the way podfile was setup). One of the things that is a must for me is the use of "use_frameworks!" inside the podfile. Hope this helps. Cheers!
[My repo](https://github.com/agu3rra/TwitterAG)
