### ISSUE TITLE
Not running well under Swift 4

### ISSUE THREAD

**Issue by kdamianakis** [bhlvoong/LBTAComponents#28]
Has anyone else tried to run the latest pod under Swift 4? I find some error messages when it runs - some can be fixed but do not know enough about the code to try and fix them all - any others observing this?

**Comment by rebeloper** [comment]
I managed to fix all errors with the Xcode built in Fix. Xcode10, Swift 4.2. I’m sure Brian will release a new version with the changes

**Comment by 8bitramen** [comment]
@rebeloper why not make a pull request with your changes so Brian can review?

**Comment by bhlvoong** [comment]
Now compatible with Swift 5. However, I am deprecating this library in favor of LBTATools.
