### ISSUE TITLE
Swift Problem?

### ISSUE THREAD

**Issue by ruelluna** [bhlvoong/LBTAComponents#29]
Here's the error.

`Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'NSLayoutConstraint for <NSLayoutXAxisAnchor:0x604000a7e5c0 "UIImageView:0x7fccbb65e150.left">: A constraint cannot be made between <NSLayoutXAxisAnchor:0x604000a7e5c0 "UIImageView:0x7fccbb65e150.left"> and <NSLayoutXAxisAnchor:0x600000a78900 "UIView:0x7fccbb469700.leading"> because their units are not compatible.'`

**Comment by rebeloper** [comment]
Could you post the code that you written for anchoring your UIImageView? Thanks

**Comment by bhlvoong** [comment]
This is because you're using incompatible anchors, this would crash with native UIKit code as well. Fix your app :)
