### ISSUE TITLE
Conversion to Swift 4.2

### ISSUE THREAD

**Issue by shi-rudo** [bhlvoong/LBTAComponents#30]
The Code needs some updating:

```
- 'NSAttributedStringKey' has been renamed to 'NSAttributedString.Key'
- 'NSLayoutFormatOptions' has been renamed to 'NSLayoutConstraint.FormatOptions'
- 'init(activityIndicatorStyle:)' has been renamed to 'init(style:)'
- 'UICollectionElementKindSectionHeader' has been renamed to 'UICollectionView.elementKindSectionHeader'
```

The issues are easy to fix, even by the user. But it would be more convenient if these issues didn't have to be fixed by the user in the first place.

**Comment by 8bitramen** [comment]
@shi-rudo why don't you make a pull request for brian to review then?

**Comment by shi-rudo** [comment]
I'm quite new to GitHub. I don't know how to do this correctly. Sorry!

**Comment by bhlvoong** [comment]
Now compatible with Swift 5. However, I am deprecating this library in favor of LBTATools.
