### ISSUE TITLE
Add UITextfield delegate to the textfield within my cells ?

### ISSUE THREAD

**Issue by jesus-rod** [bhlvoong/LBTAComponents#6]
The coolest thing about LBTAcomponents is that you don't have to dequeue cells. However, using this method does not allow me to set the delegate while dequeing the cells. 

Usually I do something like this:

```

let cell = tableView.dequeueReusableCellWithIdentifier(settingIndexPath.cellName, forIndexPath: indexPath) as! HAIConfigurationTableViewCell
            let cellInput   = cell.viewWithTag(1) as! UITextField
            
            cellInput.delegate = self
``` 

Any advice ?

**Comment by bhlvoong** [comment]
You can simply access your controller via cell.controller.

**Comment by mallibabu442** [comment]
I've been unable to import the ClassName "LBTAComponents" from Pods. I was successfully installed the LBTAComponents through Pods,bt it can't.

**Comment by dshukertjr** [comment]
I am having the same trouble as  the person who opened this issue and I do not know why this issue is closed when the problem has not been solved. 

How can I iterate through the cells and set the delegate?

**Comment by dshukertjr** [comment]
So I solved this by implementing this

```
    override func collectionView(_ collectionView: UICollectionView, cellForItemAt indexPath: IndexPath) -> CustomCell {
        
        let cell: CustomCell
        
        if let cls = datasource?.cellClass(indexPath) {
            cell = collectionView.dequeueReusableCell(withReuseIdentifier: NSStringFromClass(cls), for: indexPath) as! DatasourceCell as! CustomCell
        } else if let cellClasses = datasource?.cellClasses(), cellClasses.count > indexPath.section {
            let cls = cellClasses[indexPath.section]
            cell = collectionView.dequeueReusableCell(withReuseIdentifier: NSStringFromClass(cls), for: indexPath) as! DatasourceCell as! CustomCell
        } else if let cls = datasource?.cellClasses().first {
            cell = collectionView.dequeueReusableCell(withReuseIdentifier: NSStringFromClass(cls), for: indexPath) as! DatasourceCell as! CustomCell
        } else {
            cell = collectionView.dequeueReusableCell(withReuseIdentifier: defaultCellId, for: indexPath) as! DatasourceCell as! CustomCell
        }
        
        cell.delegate = self
        
        cell.controller = self
        cell.datasourceItem = datasource?.item(indexPath)
        return cell
    }

```
into my DatasourceController. Basically it's a copy from the LBTA framework with the cell.delegate = self added to it.

**Comment by bhlvoong** [comment]
As you can see, each cell has a "controller" property which you can use as your delegate.

**Comment by dshukertjr** [comment]
Sorry, I am relatively new to swift programing, but how exactly do I set the controller property as my delegate? There is no function that iterates through each cells in LBTAComponents's DatasourceController, right?
