### ISSUE TITLE
How update Datasource data with reload

### ISSUE THREAD

**Issue by iehsan77** [bhlvoong/LBTAComponents#7]
Hi 

I would like to reload my data in  DatasourceController when the user clicks on the refresh button. 

My Datasource shows changing in debug but no effect on collection layout views or Cells

thanks

**Comment by jesus-rod** [comment]
are you asigning the new data to the datasource? When you do that it should happen right away. For instance, on your DatasourceController you should do the following.

`self.datasource = usersDatasource`

if that does not work and I wouldnt know why, you could try:

`collectionView?.reloadData()`

**Comment by iehsan77** [comment]
hi, 

I already doing the same what you suggest but it's not reloading data in my cells.

**Comment by iehsan77** [comment]
LBTAComponents

Is there any method to reload DatasourceConstroller from scratch ??

**Comment by iehsan77** [comment]
hi

I would like to reload my data in DatasourceController when the user clicks on the refresh button.My Datasource shows changing in debug but no effect on collection layout views or Cells.

self.datasource = usersDatasource

if that does not work and I wouldnt know why, you could try:

collectionView?.reloadData()


Yes, i have tried it but no luck its shows old values on reload. If you allow me I can share my source code with you that will help to share my issue clearly. I trying to using your LBTAcomponents in my project this is my first project but I stuck on my first screen.

**Comment by jesus-rod** [comment]
Share your DataSource Code... you have to be missing something. The example project in the repo has some examples with basic usage of the library

**Comment by iehsan77** [comment]
HI,

Thanks for supporting, I have traced my issues and resolved.

once again thanks. I will disturb you if is there anything in future.



*Ehsan-ul-haq*
----------------------------------------------------
(Software & Web Development)
IPhone Android Nokia (Development)
3D Animation Services

+923232430139
http://www.iehsan.com
https://www.linkedin.com/in/iehsan/
<http://www.linkedin.com/profile/view?id=39199691&trk=tab_pro>
http://www.facebook.com/iehsan

**Comment by iehsan77** [comment]
Hi,

How are you? I have one question

How I can reload my homedatasourcecontroller from my
DatasourceCell file  item tap guests. ?


I have tried it with

collectionView?.reloadData()

but no luck


Thanks









*Ehsan-ul-haq*
----------------------------------------------------
(Software & Web Development)
IPhone Android Nokia (Development)
3D Animation Services

+923232430139
http://www.iehsan.com
https://www.linkedin.com/in/iehsan/
<http://www.linkedin.com/profile/view?id=39199691&trk=tab_pro>
http://www.facebook.com/iehsan

**Comment by bhlvoong** [comment]
You just need to update the datasource object and call reloadData.  You can look at the pod source code to see whats going on.

**Comment by Gamshan** [comment]
I am also have same issue. In my case I have an API call minor number changes from ViewDidLoad API.
I set the dataSource "self.datasource = usersDatasource", "self.collectionView?.reloadData()" in DataSourceController when api is success. But no luck It is not reload.
